repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Frontend hooks
  - repo: local
    hooks:
      - id: frontend-typescript-check
        name: Frontend TypeScript Check
        entry: bash -c 'cd frontend && bun run tsc --noEmit'
        language: system
        files: ^frontend/.*\.(ts|tsx)$
        pass_filenames: false
        stages: [commit]

      - id: frontend-test
        name: Frontend Tests
        entry: bash -c 'cd frontend && bun test'
        language: system
        files: ^frontend/.*\.(js|ts|tsx)$
        pass_filenames: false
        stages: [commit]

  # Backend hooks
  - repo: local
    hooks:
      - id: backend-test
        name: Backend Tests
        entry: bash -c 'cd backend && uv run pytest'
        language: system
        files: ^backend/.*\.py$
        pass_filenames: false
        stages: [commit]

      - id: backend-format
        name: Backend Format
        entry: bash -c 'cd backend && uv run black .'
        language: system
        files: ^backend/.*\.py$
        pass_filenames: false
        stages: [commit]
